title: Coordinates to Canvas
description: A Research Blog About a Software Renderer in Three.js
Author: Ryan Bissett
source: docs
theme: jekyll-theme-clean-blog

baseurl: '/3dage_renderer'
url: 'https://pipding.github.io/'